### ISSUE TITLE
Sandboxing

### ISSUE THREAD

**Issue by 1024jp** [coteditor/CotEditor#369]
To release an application in Apple's App Store, it must be sandboxed anyway.

- [x] enable Sandbox
- [x] #399 sandbox `cot` command-line tool
- [x] #340 drop authopen
- [x] #396 redesign command-line installer
- [x] #394 separate Sparkle support
- [x] #395 migrate script menu location

**Comment by 1024jp** [comment]
The all of sandboxing issues are now once resolved.
